// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (conversation_id, friendship_id, created_at, updated_at)
VALUES (
	gen_random_uuid(),
    $1,
	NOW(),
	NOW()
)
RETURNING conversation_id, friendship_id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, friendshipID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, friendshipID)
	var i Conversation
	err := row.Scan(
		&i.ConversationID,
		&i.FriendshipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConvoBetweenUsers = `-- name: GetConvoBetweenUsers :one
SELECT c.conversation_id, c.friendship_id, c.created_at, c.updated_at
FROM conversations c
JOIN friendship f ON c.friendship_id = f.friendship_id
WHERE (f.sender_id = $1 AND f.receiver_id = $2)
   OR (f.sender_id = $2 AND f.receiver_id = $1)
`

type GetConvoBetweenUsersParams struct {
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) GetConvoBetweenUsers(ctx context.Context, arg GetConvoBetweenUsersParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConvoBetweenUsers, arg.SenderID, arg.ReceiverID)
	var i Conversation
	err := row.Scan(
		&i.ConversationID,
		&i.FriendshipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
