// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (conversation_id, friendship_id, created_at, updated_at)
VALUES (
	gen_random_uuid(),
    $1,
	NOW(),
	NOW()
)
RETURNING conversation_id, friendship_id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, friendshipID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, friendshipID)
	var i Conversation
	err := row.Scan(
		&i.ConversationID,
		&i.FriendshipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConvoByFriendshipID = `-- name: GetConvoByFriendshipID :one
SELECT conversation_id, friendship_id, created_at, updated_at FROM conversations
WHERE friendship_id = $1
`

func (q *Queries) GetConvoByFriendshipID(ctx context.Context, friendshipID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConvoByFriendshipID, friendshipID)
	var i Conversation
	err := row.Scan(
		&i.ConversationID,
		&i.FriendshipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
