// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friendship (friendship_id, sender_id, receiver_id, friend_status, created_at, updated_at)
VALUES (
	gen_random_uuid(),
    $1,
    $2,
    'pending',
	NOW(),
	NOW()
)
RETURNING friendship_id, sender_id, receiver_id, friend_status, created_at, updated_at
`

type CreateFriendRequestParams struct {
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, createFriendRequest, arg.SenderID, arg.ReceiverID)
	var i Friendship
	err := row.Scan(
		&i.FriendshipID,
		&i.SenderID,
		&i.ReceiverID,
		&i.FriendStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendship WHERE friendship_id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, friendshipID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, friendshipID)
	return err
}

const updateFriendStatus = `-- name: UpdateFriendStatus :exec
UPDATE friendship
SET friend_status = $2, updated_at = NOW()
WHERE friendship_id = $1
`

type UpdateFriendStatusParams struct {
	FriendshipID uuid.UUID
	FriendStatus string
}

func (q *Queries) UpdateFriendStatus(ctx context.Context, arg UpdateFriendStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFriendStatus, arg.FriendshipID, arg.FriendStatus)
	return err
}
