// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (message_id, room_id, user_id, content, message_type, sent_at)
VALUES (
	gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
	NOW()
)
RETURNING message_id, room_id, user_id, content, message_type, sent_at
`

type CreateMessageParams struct {
	RoomID      uuid.UUID
	UserID      uuid.UUID
	Content     string
	MessageType string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.RoomID,
		arg.UserID,
		arg.Content,
		arg.MessageType,
	)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.MessageType,
		&i.SentAt,
	)
	return i, err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT 
    message.message_id, message.room_id, message.user_id, message.content, message.message_type, message.sent_at,
    users.username
FROM message
JOIN users ON message.user_id = users.id
WHERE message.room_id = $1
ORDER BY message.sent_at ASC
LIMIT $2 OFFSET $3
`

type GetRecentMessagesParams struct {
	RoomID uuid.UUID
	Limit  int32
	Offset int32
}

type GetRecentMessagesRow struct {
	MessageID   uuid.UUID
	RoomID      uuid.UUID
	UserID      uuid.UUID
	Content     string
	MessageType string
	SentAt      time.Time
	Username    string
}

func (q *Queries) GetRecentMessages(ctx context.Context, arg GetRecentMessagesParams) ([]GetRecentMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMessagesRow
	for rows.Next() {
		var i GetRecentMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.MessageType,
			&i.SentAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
