// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (message_id, room_id, user_id, content, message_type, sent_at)
VALUES (
	gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
	NOW()
)
RETURNING message_id, room_id, user_id, content, message_type, sent_at
`

type CreateMessageParams struct {
	RoomID      uuid.UUID
	UserID      uuid.UUID
	Content     string
	MessageType string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.RoomID,
		arg.UserID,
		arg.Content,
		arg.MessageType,
	)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.MessageType,
		&i.SentAt,
	)
	return i, err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT message_id, room_id, user_id, content, message_type, sent_at
FROM message
WHERE room_id = $1
ORDER BY sent_at ASC
LIMIT 50
`

func (q *Queries) GetRecentMessages(ctx context.Context, roomID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MessageID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.MessageType,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
