// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	MessageID   uuid.UUID
	RoomID      uuid.UUID
	UserID      uuid.UUID
	Content     string
	MessageType string
	SentAt      time.Time
}

type Room struct {
	RoomID    uuid.UUID
	RoomName  string
	CreatedAt time.Time
}

type Session struct {
	Token     string
	CreatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
}
