// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPersonalMessage = `-- name: CreatePersonalMessage :one
INSERT INTO personal_messages (message_id, conversation_id, user_id, encrypted_content, message_type, sent_at)
VALUES (
	gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
	NOW()
)
RETURNING message_id, conversation_id, user_id, encrypted_content, message_type, sent_at
`

type CreatePersonalMessageParams struct {
	ConversationID   uuid.UUID
	UserID           uuid.UUID
	EncryptedContent string
	MessageType      string
}

func (q *Queries) CreatePersonalMessage(ctx context.Context, arg CreatePersonalMessageParams) (PersonalMessage, error) {
	row := q.db.QueryRowContext(ctx, createPersonalMessage,
		arg.ConversationID,
		arg.UserID,
		arg.EncryptedContent,
		arg.MessageType,
	)
	var i PersonalMessage
	err := row.Scan(
		&i.MessageID,
		&i.ConversationID,
		&i.UserID,
		&i.EncryptedContent,
		&i.MessageType,
		&i.SentAt,
	)
	return i, err
}

const getRecentConvo = `-- name: GetRecentConvo :many
SELECT 
    p.message_id, p.conversation_id, p.user_id, p.encrypted_content, p.message_type, p.sent_at,
    users.username
FROM personal_messages p
JOIN users ON p.user_id = users.id
WHERE p.conversation_id = $1
ORDER BY p.sent_at DESC
LIMIT $2 OFFSET $3
`

type GetRecentConvoParams struct {
	ConversationID uuid.UUID
	Limit          int32
	Offset         int32
}

type GetRecentConvoRow struct {
	MessageID        uuid.UUID
	ConversationID   uuid.UUID
	UserID           uuid.UUID
	EncryptedContent string
	MessageType      string
	SentAt           time.Time
	Username         string
}

func (q *Queries) GetRecentConvo(ctx context.Context, arg GetRecentConvoParams) ([]GetRecentConvoRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentConvo, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentConvoRow
	for rows.Next() {
		var i GetRecentConvoRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ConversationID,
			&i.UserID,
			&i.EncryptedContent,
			&i.MessageType,
			&i.SentAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
