// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (room_id, room_name, created_at)
VALUES (
	gen_random_uuid(),
    $1,
	NOW()
)
RETURNING room_id, room_name, created_at
`

func (q *Queries) CreateRoom(ctx context.Context, roomName string) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, roomName)
	var i Room
	err := row.Scan(&i.RoomID, &i.RoomName, &i.CreatedAt)
	return i, err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT room_id, room_name, created_at
FROM rooms
WHERE room_name = $1
`

func (q *Queries) GetRoomByName(ctx context.Context, roomName string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByName, roomName)
	var i Room
	err := row.Scan(&i.RoomID, &i.RoomName, &i.CreatedAt)
	return i, err
}
