// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (room_id, owner_id, room_name, created_at)
VALUES (
	gen_random_uuid(),
    $1,
	$2,
	NOW()
)
RETURNING room_id, owner_id, room_name, created_at
`

type CreateRoomParams struct {
	OwnerID  uuid.UUID
	RoomName string
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.OwnerID, arg.RoomName)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.OwnerID,
		&i.RoomName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE room_id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, roomID)
	return err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT room_id, owner_id, room_name, created_at
FROM rooms
WHERE room_name = $1
`

func (q *Queries) GetRoomByName(ctx context.Context, roomName string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByName, roomName)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.OwnerID,
		&i.RoomName,
		&i.CreatedAt,
	)
	return i, err
}

const getRooms = `-- name: GetRooms :many
SELECT room_id, owner_id, room_name, created_at
FROM rooms
WHERE owner_id = $1
`

func (q *Queries) GetRooms(ctx context.Context, ownerID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRooms, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.OwnerID,
			&i.RoomName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
